---
# tasks file for ansible-role-jenkins-master

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ jenkins-master_log_dir }}"
    mode: 0755
    owner: "{{ jenkins-master_user }}"
    group: "{{ jenkins-master_group }}"
    state: directory
  notify: Restart jenkins-master

- name: Create db directory
  file:
    path: "{{ jenkins-master_db_dir }}"
    mode: 0755
    owner: "{{ jenkins-master_user }}"
    group: "{{ jenkins-master_group }}"
    state: directory
  notify: Restart jenkins-master

- name: Create jenkins-master.conf
  template:
    src: jenkins-master.conf.j2
    dest: "{{ jenkins-master_conf_file }}"
    validate: echo %s
  notify: Restart jenkins-master

- name: Start jenkins-master
  service:
    name: "{{ jenkins-master_service }}"
    enabled: true
    state: started
